apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task-container
        image: ghcr.io/oleksii-stepanyk/gh-actions-workshop:bc5d627
        ports:
        - containerPort: 8080
