apiVersion: v1
kind: Service
metadata:
  name: task-nodeport
spec:
  selector:
    app: task
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008