name: Apply

on:
  push:
    branches: [ main ]

jobs:
  apply:
    name: Apply new config
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create SSH Key
      run: |
        echo "${{ secrets.PUB_KEY }}" > pubkey.pem
        chmod 777 pubkey.pem

    - name: SSH and Apply config
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.EC2_IP }}
        user: ubuntu
        key: pubkey.pem
        port: 22
        connect_timeout: 10s
        first_ssh: |
          echo "Test"
        scp: |
          app.yaml => /home/ubuntu/
          nodeport.yaml => /home/ubuntu/
        last_ssh: |
          cd ~
          kubectl apply -f app.yaml
          kubectl apply -f nodeport.yaml
