name: Apply

on:
  push:
    branches: [ main ]

jobs:
  apply:
    name: Apply new config
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Copy files to EC2
      uses: cross-the-world/scp-pipeline@master
      with:
       host: ${{ secrets.EC2_IP }}
       user: "ubuntu"
       key: ${{ secrets.PUB_KEY }}
       local: '.'
       remote: /home/ubuntu/
       scp: |
         app.yaml => "/home/ubuntu/"
         nodeport.yaml => "/home/ubuntu/"
    - name: SSH to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
       host: ${{ secrets.EC2_IP }}
       username: "ubuntu"
       key: ${{ secrets.PUB_KEY }}
       script: |
         kubectl apply -f app.yaml
         kubectl apply -f nodeport.yaml
